# ref: https://circleci.com/docs/2.0/orb-intro/#section=configuration
# https://circleci.com/developer/orbs/orb/circleci/node
jobs:
  test:
    executor:
      name: node/default
      # ref: https://hub.docker.com/r/cimg/node/tags
      tag: 'lts'
    steps:
      - checkout

      # we need submodule from core
      # let us try to init the submodule
      - run:
          command: git submodule update --init --recursive
          name: Init git submodule

      - node/install-packages:
          pkg-manager: yarn

      - run:
          command: yarn test
          name: Run YARN tests
orbs:
  node: circleci/node@4.1
version: 2.1
workflows:
  test_vue_speedometer:
    jobs:
      - test